[workspace]
members = [
  "bins/vulcan-dhcpd",
  "bins/vulcan-cli",
  "libs/binbuf",
  "libs/radvd",
  "libs/dhcp"
]

[workspace.dependencies]
tokio = { version = "1.21.2", features = ["net", "macros", "rt", "time"] }
binum = { path = "../../Techassi/binum" }
binbuf = { path = "./libs/binbuf" }
thiserror = "1.0.37"
rand = "0.8.5"
