[workspace]
members = ["crates/*"]

[workspace.dependencies]
tokio = { version = "1.21.2", features = ["net", "macros", "rt", "rt-multi-thread", "time"] }
binbuf = { path = "../../Techassi/binbuf" }
thiserror = "1.0.37"
rand = "0.8.5"
