[config]
default_to_workspace = false

[tasks.build-dhcpc]
command = "cargo"
args = ["build" , "-p", "vulcan-dhcpc"]

[tasks.run-dhcpc]
command = "sudo"
args = ["./target/debug/vulcan-dhcpc"]
dependencies = ["build-dhcpc"]

[tasks.build-dhcpd]
command = "cargo"
args = ["build" , "-p", "vulcan-dhcpd"]

[tasks.run-dhcpd]
command = "sudo"
args = ["./target/debug/vulcan-dhcpd", "--config", "extra/vulcan-dhcpd.toml"]
dependencies = ["build-dhcpd"]