[package]
name = "dhcp"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
binbuf = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
network-interface = "0.1.6"

[lib]
name = "dhcp"
path = "src/lib.rs"
