[package]
name = "dhcp"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
binbuf = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }

[lib]
name = "dhcp"
path = "src/lib.rs"
