[package]
name = "vulcan-dhcpd"
version = "0.0.1"
edition = "2021"

[dependencies]
dhcp = { path = "../../crates/lib-dhcp" }
thiserror = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
toml = { workspace = true }
